name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Stáhne kód
      - name: Checkout repository
        uses: actions/checkout@v4

      # Nastaví stejnou verzi Node jako lokálně (pravděpodobně 18 nebo 20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Nainstaluje balíčky
      - name: Install dependencies
        run: npm install

      # Spustí build
      - name: Build project
        run: npm run build

      # Deploy na Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
